(defkind (= [])       nil)
(defkind #'number?    number)
(defkind #'string?    string)
(defkind #'symbol?    symbol)
(defkind #'cons?      cons)
(defkind #'function?  function)
(defkind #'absvector? absvector)
(defkind #'vector?    vector)
(defkind #'tuple?     tuple)
(defkind #'stack?     stack)
(defkind #'queue?     queue)
\\ (defkind #'pv? pv)
